---
config:
  flowchart:
    curve: linear
---
graph TD;
	__start__([<p>__start__</p>]):::first
	parse(parse)
	analyze(analyze)
	generate(generate)
	validate(validate)
	persist(persist)
	evaluate(evaluate)
	__end__([<p>__end__</p>]):::last
	__start__ --> parse;
	analyze --> generate;
	generate --> validate;
	parse -.-> analyze;
	parse -.-> persist;
	persist --> evaluate;
	validate -.-> generate;
	validate -.-> persist;
	evaluate --> __end__;
	classDef default fill:#f2f0ff,line-height:1.2
	classDef first fill-opacity:0
	classDef last fill:#bfb6fc
